feat: fallback to nodeport if ingress url is not present (#68)

diff --git a/scripts/zap/trigger_zap_scans b/scripts/zap/trigger_zap_scans
--- a/scripts/zap/trigger_zap_scans
+++ b/scripts/zap/trigger_zap_scans
@@ -61,6 +61,18 @@
     # reading back the param that was exported in the dynamic-scan setup stage
     export URL
     URL="$(get_env app-url "${APP_URL}")"
+
+    if [ -z  "${URL}"  ] || [[  "${URL}" = "http://null"  ]]; then
+      
+      ZAP_SCRIPTS_DIR="${WORKSPACE}/$(get_env zap-core-scripts "")"
+      ZAP_EVIDENCE_TYPE="$(get_env zap_evidence_type "com.ibm.dynamic_scan")"
+      ZAP_STATUS_TYPE="failure"
+      source "${ZAP_SCRIPTS_DIR}"/report
+
+      echo "Unable to get Application URL....."
+      exit 1
+    fi 
+
     set_env "target-application-server-url" "${URL}"
 
     # set the swagger defintion file(s) comma separated if required
